name: The Caterpillar Project
description: A large suite of dark matter simulations of Milky Way-sized galaxies.
url: http://caterpillarproject.org
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]
highlighter: pygments
permalink: /about/:title